Migrate to netstandards
Flexberry/NewPlatform.Flexberry.GIS pull request #2
Opened 2020-11-06 15:00 UTC by kuzkok

2020-11-09 05:57 UTC, bratchikov requested changes
Давай сразу добавим .travis.yml в этот PR, чтобы проверить, что хотя бы сборка проходит.

2020-11-09 05:57 UTC, bratchikov commented on NewPlatform.Flexberry.GIS.DataLinks.nuspec
> -    <version>0.4.0-beta11</version>
Давай перед этим мерджем выпустим версию NuGet-пакета 0.4.0?

2020-11-09 05:57 UTC, bratchikov commented on NewPlatform.Flexberry.GIS.DataLinks.nuspec
>      <iconUrl>http://flexberry.net/portals/_default/skins/flexerry/images/logo_last.png</iconUrl>
Этот адрес недействительный, посмотри как в ORM.

2020-11-09 05:57 UTC, bratchikov commented on NewPlatform.Flexberry.GIS.DataLinks.nuspec
> +        <dependency id="NewPlatform.Flexberry.ORM.PostgresDataService" version="6.0.0-beta11" />
А другие СУБД эти объекты данных в принципе не поддерживают?

2020-11-09 05:57 UTC, bratchikov commented on NewPlatform.Flexberry.GIS.DataLinks/NewPlatform.Flexberry.GIS.DataLinks.csproj
> +    <AssemblyName>NewPlatform.Flexberry.GIS.DataLinks</AssemblyName>
А разве это не объекты данных? Давай оставим имя папки, проекта и сборки в соответствии с тем, как генерирует Flexberry Designer? Там теперь вместо (Objects) генерируется .Objects, что вполне работает.

2020-11-09 06:04 UTC, kuzkok commented on NewPlatform.Flexberry.GIS.DataLinks.nuspec
> +        <dependency id="NewPlatform.Flexberry.ORM.PostgresDataService" version="6.0.0-beta11" />
Они универсальные, тут в коде есть проверка if (DataService is Postgres...), я пока только миграцию делаю, без причёсывания

2020-11-09 06:05 UTC, kuzkok commented on NewPlatform.Flexberry.GIS.DataLinks.nuspec
> -    <version>0.4.0-beta11</version>
0.3.0 тогда уж.

2020-11-09 06:35 UTC, bratchikov commented on NewPlatform.Flexberry.GIS.DataLinks.nuspec
> +        <dependency id="NewPlatform.Flexberry.ORM.PostgresDataService" version="6.0.0-beta11" />
Ок, пусть так.

2020-11-10 17:15 UTC, bratchikov approved these changes

2020-11-10 17:15 UTC, merged